export const config ={
    "key": "",
    "baseCalls": {
      "oneCall": {
        "baseUrl": "https://api.openweathermap.org/data/3.0/onecall?",
      },
      "geocoding": {
        "baseUrl": "http://api.openweathermap.org/geo/1.0/direct?q=",
      }
    },
    "coordinates": {
      "sea":{
        "lat": "18.272853",
        "lon": "-69.790003"
      }
    },
    "cityName": "London",
    "typoName": "Medellins",
  }